##UBUNTU-v20.04##
UBUNTU_ISO="https://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso"
##BASE-MOD-v0.3.1##
BASE_REPO="git@github.com:Netping/DKSF_90.git"
##ZABBIX-v5.2.7##
ZABBIX_REPO="git@github.com:0zZz1k/DKSL_APP_ZABBIX.git"
##NPSERVERSETTINGS##
NPSETTINGS_REPO="git@github.com:Netping/DKST90_NpServerSettings.git"
##BORG-v.1.1.16##
BORG_REPO="git@github.com:Netping/DKSL_APP_BORG.git"
