##UBUNTU##
UBUNTU_ISO="https://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso"
##ZABBIX##
ZABBIX_TAG="0.3.1"
ZABBIX_REPO="git@github.com:0zZz1k/DKSL_APP_ZABBIX.git"
##NPSERVERSETTINGS##
NPSETTINGS_TAG=0.3.1
NPSETTINGS_REPO="git@github.com:Netping/DKST90_NpServerSettings.git"
##BORG##
BORG_TAG=0.3.1
BORG_REPO="git@github.com:0zZz1k/DKSL_APP_BORG.git"
